apiVersion: v2
appVersion: "0.9.8"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.5.6
deprecated: false
description: rTorrent Docker Image
home: https://github.com/Maxwellwr/TrueNasCharts
icon: https://rtorrent-docs.readthedocs.io/en/latest/_static/logo.png
keywords:
  - rtorrent
  - torrrent
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: Maxwell
    url: https://truecharts.org
name: rtorrent
sources:
  - https://github.com/Maxwellwr/TrueNasCharts/tree/dev/charts/dev/rtorrent
  - https://github.com/rakshasa/rtorrent
type: application
version: 1.0.0
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
