annotations:
  max_scale_version: 23.10.2
  min_scale_version: 23.10.0
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: media
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.12"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 2.11.1
dependencies:
  - name: common
    version: 17.2.29
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: rTorrent Docker Image
home: https://github.com/Maxwellwr/TrueNasCharts
icon: https://rtorrent-docs.readthedocs.io/en/latest/_static/logo.png
keywords:
  - rtorrent
  - torrrent
kubeVersion: ">=1.24.0-0"
maintainers:
  - email: info@truecharts.org
    name: Maxwell
    url: https://truecharts.org
name: rtorrent
sources:
  - https://github.com/Maxwellwr/TrueNasCharts/tree/dev/charts/dev/rtorrent
  - https://github.com/rakshasa/rtorrent
type: application
version: 1.0.2
