image:
  repository: ghcr.io/crazy-max/rtorrent-rutorrent
  pullPolicy: IfNotPresent
  tag: 4.2.9-0.9.8_2-0.13.8_2

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 8080
        targetPort: 8080
  torrent:
    enabled: true
    ports:
      torrent:
        enabled: true
        port: 50000
        targetPort: 50000
  dht:
    enabled: true
    ports:
      dht:
        enabled: true
        port: 6881
        targetPort: 6881
  dhtudp:
    enabled: true
    ports:
      dhtudp:
        enabled: true
        port: 6881
        targetPort: 6881
        protocol: UDP
  xmlrpc:
    enabled: true
    ports:
      xmlrpc:
        enabled: true
        port: 8000
        targetPort: 8000
  webdav:
    enabled: true
    ports:
      webdav:
        enabled: true
        port: 9000
        targetPort: 9000

persistence:
  data:
    enabled: true
    mountPath: "/data"
  downloads:
    enabled: true
    mountPath: "/downloads"
  password:
    enabled: true
    mountPath: "/passwd"
